import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Sider from "@/components/Sider/Sider";
import styles from "./layout.module.scss";

import { Rubik } from 'next/font/google'
import QuestionForm from "@/components/QuestionForm/QuestionForm";
import Logos from "@/components/Logos/Logos";
import Footer from "@/components/Footer/Footer";
import Questions from "@/components/Questions/Questions";
import RequestForm from "@/components/RequestForm/RequestForm";

const rubik = Rubik({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={[styles.wrp, rubik.className].join(" ")}>
        <AntdRegistry>

          <div className={styles.content}>
            <Header />
            {children}
            <RequestForm />
            <Questions />
            <QuestionForm />
            <Logos />
            <Header bg={'#E4E9F0'} isShowMenu={false} isShowPhone={true} />
            <Footer />
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
